language: go

go:
  - 1.7
  - 1.8
  - 1.9

install:
  - go get gopkg.in/yaml.v2
  - go get github.com/stretchr/testify
  - go get github.com/golang/lint/golint

script:
  - go test -v
  - go vet
  - golint
